# Generic infos

title: The Critical Git
email: sal.penitente@gmail.com
description: "A blog made of stories about useless tinkering and other weird stuff."
url: "https://backsofangels.github.io"
permalink: /:title/

# Author infos

author:
  name: Salvatore Penitente
  github_username:  backsofangels

# Theme
theme: jekyll-theme-cayman
show_downloads: false

# Plugins

plugins:
  - jekyll-feed
  - jekyll-seo-tag

markdown: kramdown
kramdown:
  syntax_highlighter: rouge