# Generic infos

title: Salvatore's Blog
email: sal.penitente@gmail.com
description: >- 
  A blog made of stories about useless tinkering
baseurl: ""
url: "https://backsofangels.github.io"
permalink: /:title/

# Author infos

author:
  name: Salvatore Penietnte
  github_username:  backsofangels

# Theme
theme: jekyll-theme-cayman

# Plugins

plugins:
  - jekyll-feed
  - jekyll-seo-tag