# Generic infos

title: "The Critical Git"
email: sal.penitente@gmail.com
description: "A blog made of stories about useless tinkering and other weird stuff."
url: "https://backsofangels.github.io"
permalink: /:title/

# Author infos

author:
  name: The Critical Git
  github_username:  backsofangels

# Theme
theme: jekyll-theme-cayman
show_downloads: false

# Plugins

plugins:
  - jekyll-feed
  - jekyll-seo-tag

markdown: kramdown
kramdown:
  input: GFM        # GitHub Flavored Markdown
  syntax_highlighter: rouge
  auto_ids: true    # Genera automaticamente id="titolo" per gli anchor link
  hard_wrap: false

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - README.md
  - .sass-cache